[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/poem-middleware"
]
exclude = [
    "projects/.DS_Store",
]


[profile.release]
lto = true
panic = "abort"

[workspace.dependencies.sqlx]
version = "0.8.3"
default-features = false
